// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    IconPlay: typeof import('./components/Icon/IconPlay.vue')['default']
    Images: typeof import('./components/Images.vue')['default']
    Introduce: typeof import('./components/Introduce.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongsList: typeof import('./components/SongsList.vue')['default']
  }
}

export {}
